export const STABLECOINS = new Set([
  'USDT','USDC','BUSD','DAI','TUSD','USDP','GUSD','FRAX','LUSD',
  'SUSD','USDD','USTC','FDUSD','PYUSD','CRVUSD','USDX','USDS',
  'EURC','EUROC','EURT','USDE','USDJ','HUSD','DOLA','MIM','ALUSD',
  'OUSD','USDK','USDI','CUSD','GHO','CEUR','AGEUR','EURS','SEUR',
  'STEUR','EURA','EUSD','USDB','USDL','USDZ','LISUSD'
]);

export const WRAPPED = new Set([
  'WBTC','WETH','WBNB','WSOL','STETH','WSTETH','CBETH','RETH',
  'FRXETH','SFRXETH','WEETH','EZETH','RSETH','PXETH','WMATIC',
  'WAVAX','WFTM','WONE','WKLAY','WROSE'
]);