// Crypto universe — 196 assets with verified source coverage
// (189 base + 7 targeted additions; "Other" bucket trimmed via category moves)

export const CRYPTO_UNIVERSE = [
  // Layer 1
  { symbol: 'BTC', name: 'Bitcoin', theme: 'Layer 1', tier: 'Core', subtheme: 'Bitcoin' },
  { symbol: 'ETH', name: 'Ethereum', theme: 'Layer 1', tier: 'Core', subtheme: 'Smart Contract L1' },
  { symbol: 'BNB', name: 'BNB', theme: 'Layer 1', tier: 'Core', subtheme: 'Exchange L1' },
  { symbol: 'XRP', name: 'XRP', theme: 'Layer 1', tier: 'Core', subtheme: 'Payments L1' },
  { symbol: 'SOL', name: 'Solana', theme: 'Layer 1', tier: 'Core', subtheme: 'Smart Contract L1' },
  { symbol: 'TRX', name: 'TRON', theme: 'Layer 1', tier: 'Core', subtheme: 'Smart Contract L1' },
  { symbol: 'HYPE', name: 'Hyperliquid', theme: 'Layer 1', tier: 'Core', subtheme: 'Perpetuals L1' },
  { symbol: 'ADA', name: 'Cardano', theme: 'Layer 1', tier: 'Core', subtheme: 'Smart Contract L1' },
  { symbol: 'GRAM', name: 'Gram (prev. Toncoin)', theme: 'Layer 1', tier: 'Core', subtheme: 'Smart Contract L1' },
  { symbol: 'BCH', name: 'Bitcoin Cash', theme: 'Layer 1', tier: 'Core', subtheme: 'Payments' },
  { symbol: 'LTC', name: 'Litecoin', theme: 'Layer 1', tier: 'Core', subtheme: 'Payments' },
  { symbol: 'AVAX', name: 'Avalanche', theme: 'Layer 1', tier: 'Core', subtheme: 'Smart Contract L1' },
  { symbol: 'SUI', name: 'Sui', theme: 'Layer 1', tier: 'Core', subtheme: 'Smart Contract L1' },
  { symbol: 'NEAR', name: 'NEAR Protocol', theme: 'Layer 1', tier: 'Core', subtheme: 'Smart Contract L1' },
  { symbol: 'DOT', name: 'Polkadot', theme: 'Layer 1', tier: 'Core', subtheme: 'Smart Contract L1' },
  { symbol: 'ICP', name: 'Internet Computer', theme: 'Layer 1', tier: 'Core', subtheme: 'Smart Contract L1' },
  { symbol: 'ETC', name: 'Ethereum Classic', theme: 'Layer 1', tier: 'Active', subtheme: 'Smart Contract L1' },
  { symbol: 'KAS', name: 'Kaspa', theme: 'Layer 1', tier: 'Active', subtheme: 'Payments' },
  { symbol: 'ATOM', name: 'Cosmos Hub', theme: 'Layer 1', tier: 'Core', subtheme: 'Interoperability' },
  { symbol: 'FLR', name: 'Flare', theme: 'Layer 1', tier: 'Active', subtheme: 'Smart Contract L1' },
  { symbol: 'A', name: 'Vaulta', theme: 'Layer 1', tier: 'Active', subtheme: 'Smart Contract L1' },
  // MET moved to DeFi (it's a DEX, not an L1)
  { symbol: 'EGLD', name: 'MultiversX', theme: 'Layer 1', tier: 'Active', subtheme: 'Smart Contract L1' },
  { symbol: 'GAS', name: 'Gas', theme: 'Layer 1', tier: 'Active', subtheme: 'Smart Contract L1' },
  { symbol: 'QTUM', name: 'Qtum', theme: 'Layer 1', tier: 'Active', subtheme: 'Smart Contract L1' },
  { symbol: 'RVN', name: 'Ravencoin', theme: 'Layer 1', tier: 'Active', subtheme: 'Asset Issuance' },
  { symbol: 'BERA', name: 'Berachain', theme: 'Layer 1', tier: 'Active', subtheme: 'Smart Contract L1' },
  { symbol: 'PROS', name: 'Pharos', theme: 'Layer 1', tier: 'Active', subtheme: 'Smart Contract L1' },
  { symbol: 'ZIL', name: 'Zilliqa', theme: 'Layer 1', tier: 'Active', subtheme: 'Sharding' },
  { symbol: 'KSM', name: 'Kusama', theme: 'Layer 1', tier: 'Active', subtheme: 'Parachain Testnet' },
  { symbol: 'ZETA', name: 'ZetaChain', theme: 'Layer 1', tier: 'Active', subtheme: 'Smart Contract L1' },
  { symbol: 'MINA', name: 'Mina Protocol', theme: 'Layer 1', tier: 'Active', subtheme: 'Succinct Blockchain' },
  { symbol: 'FLOW', name: 'Flow', theme: 'Layer 1', tier: 'Active', subtheme: 'Smart Contract L1' },
  { symbol: 'KAVA', name: 'Kava', theme: 'Layer 1', tier: 'Active', subtheme: 'Smart Contract L1' },
  { symbol: 'CKB', name: 'Nervos Network', theme: 'Layer 1', tier: 'Active', subtheme: 'Smart Contract L1' },
  { symbol: 'MOVE', name: 'Movement', theme: 'Layer 1', tier: 'Active', subtheme: 'Smart Contract L1' },
  { symbol: 'BR', name: 'Bedrock', theme: 'Layer 1', tier: 'Active', subtheme: 'Smart Contract L1' },
  // Moved from Other (these are L1s that were miscategorized)
  { symbol: 'ONT', name: 'Ontology', theme: 'Layer 1', tier: 'Active', subtheme: 'Smart Contract L1' },
  { symbol: 'CTC', name: 'Creditcoin', theme: 'Layer 1', tier: 'Active', subtheme: 'Smart Contract L1' },
  { symbol: 'ASTR', name: 'Astar', theme: 'Layer 1', tier: 'Active', subtheme: 'Smart Contract L1' },
  // Layer 2
  { symbol: 'MNT', name: 'Mantle', theme: 'Layer 2', tier: 'Active', subtheme: 'Rollup' },
  { symbol: 'POL', name: 'POL (ex-MATIC)', theme: 'Layer 2', tier: 'Active', subtheme: 'Rollup' },
  { symbol: 'ZK', name: 'ZKsync', theme: 'Layer 2', tier: 'Active', subtheme: 'Rollup' },
  { symbol: 'IMX', name: 'Immutable', theme: 'Layer 2', tier: 'Active', subtheme: 'Gaming L2' },
  { symbol: 'SOON', name: 'SOON', theme: 'Layer 2', tier: 'Active', subtheme: 'Rollup' },
  { symbol: 'LINEA', name: 'Linea', theme: 'Layer 2', tier: 'Active', subtheme: 'Rollup' },
  { symbol: 'MEGA', name: 'MegaETH', theme: 'Layer 2', tier: 'Active', subtheme: 'Rollup' },
  // DeFi
  { symbol: 'UNI', name: 'Uniswap', theme: 'DeFi', tier: 'Core', subtheme: 'DEX' },
  { symbol: 'AAVE', name: 'Aave', theme: 'DeFi', tier: 'Core', subtheme: 'Lending' },
  { symbol: 'SKY', name: 'Sky', theme: 'DeFi', tier: 'Active', subtheme: 'Stablecoin' },
  { symbol: 'MORPHO', name: 'Morpho', theme: 'DeFi', tier: 'Active', subtheme: 'Lending' },
  { symbol: 'DEXE', name: 'DeXe', theme: 'DeFi', tier: 'Active', subtheme: 'DAO' },
  { symbol: 'JST', name: 'JUST', theme: 'DeFi', tier: 'Active', subtheme: 'Stablecoin' },
  { symbol: 'ENA', name: 'Ethena', theme: 'DeFi', tier: 'Core', subtheme: 'Stablecoin' },
  { symbol: 'JUP', name: 'Jupiter', theme: 'DeFi', tier: 'Active', subtheme: 'DEX' },
  { symbol: 'RLB', name: 'Rollbit Coin', theme: 'DeFi', tier: 'Active', subtheme: 'Gambling' },
  { symbol: 'CVX', name: 'Convex Finance', theme: 'DeFi', tier: 'Active', subtheme: 'DeFi' },
  { symbol: 'KMNO', name: 'Kamino', theme: 'DeFi', tier: 'Active', subtheme: 'Lending' },
  { symbol: 'MAGMA', name: 'Magma Finance', theme: 'DeFi', tier: 'Active', subtheme: 'DeFi' },
  { symbol: 'COW', name: 'CoW Protocol', theme: 'DeFi', tier: 'Active', subtheme: 'DEX Aggregator' },
  { symbol: 'ORCA', name: 'Orca', theme: 'DeFi', tier: 'Active', subtheme: 'DEX' },
  { symbol: 'SNX', name: 'Synthetix', theme: 'DeFi', tier: 'Active', subtheme: 'Derivatives' },
  { symbol: 'FLUID', name: 'Fluid', theme: 'DeFi', tier: 'Active', subtheme: 'Liquidity' },
  { symbol: 'ZRX', name: '0x Protocol', theme: 'DeFi', tier: 'Active', subtheme: 'DEX Infrastructure' },
  { symbol: 'LDO', name: 'Lido DAO', theme: 'DeFi', tier: 'Active', subtheme: 'Liquid Staking' },
  { symbol: 'YFI', name: 'yearn.finance', theme: 'DeFi', tier: 'Active', subtheme: 'DeFi' },
  { symbol: 'GMX', name: 'GMX', theme: 'DeFi', tier: 'Active', subtheme: 'Derivatives' },
  // Moved from Layer 1 (MET is a DEX, not an L1)
  { symbol: 'MET', name: 'Meteora', theme: 'DeFi', tier: 'Active', subtheme: 'DEX' },
  // Moved from Other (1INCH is a DEX aggregator)
  { symbol: '1INCH', name: '1INCH', theme: 'DeFi', tier: 'Active', subtheme: 'DEX Aggregator' },
  // Moved from Other (BLUR is an NFT marketplace with DeFi mechanics)
  { symbol: 'BLUR', name: 'Blur', theme: 'DeFi', tier: 'Active', subtheme: 'NFT/DeFi' },
  // Targeted additions — DeFi
  { symbol: 'CRV', name: 'Curve DAO', theme: 'DeFi', tier: 'Active', subtheme: 'DEX' },
  { symbol: 'LIT', name: 'Lighter DEX', theme: 'DeFi', tier: 'Active', subtheme: 'DEX' },
  { symbol: 'JTO', name: 'Jito', theme: 'DeFi', tier: 'Active', subtheme: 'MEV/Staking' },
  // AI & Compute
  { symbol: 'TAO', name: 'Bittensor', theme: 'AI & Compute', tier: 'Active', subtheme: 'AI Protocol' },
  { symbol: 'WLD', name: 'Worldcoin', theme: 'AI & Compute', tier: 'Active', subtheme: 'AI Identity' },
  { symbol: 'RENDER', name: 'Render (ex-RNDR)', theme: 'AI & Compute', tier: 'Core', subtheme: 'GPU/Compute' },
  { symbol: 'DATA', name: 'Data Network', theme: 'AI & Compute', tier: 'Active', subtheme: 'AI Protocol' },
  { symbol: 'GLM', name: 'Golem', theme: 'AI & Compute', tier: 'Active', subtheme: 'Compute' },
  { symbol: 'ATH', name: 'Aethir', theme: 'AI & Compute', tier: 'Active', subtheme: 'GPU Cloud' },
  { symbol: 'ARC', name: 'AI Rig Complex', theme: 'AI & Compute', tier: 'Active', subtheme: 'AI Protocol' },
  { symbol: 'LPT', name: 'Livepeer', theme: 'AI & Compute', tier: 'Active', subtheme: 'Video/Transcoding' },
  { symbol: 'ARKM', name: 'Arkham', theme: 'AI & Compute', tier: 'Active', subtheme: 'AI Protocol' },
  { symbol: 'UAI', name: 'UnifAI Network', theme: 'AI & Compute', tier: 'Active', subtheme: 'AI Protocol' },
  { symbol: 'Q', name: 'Quack AI', theme: 'AI & Compute', tier: 'Active', subtheme: 'AI Protocol' },
  { symbol: 'IO', name: 'io.net', theme: 'AI & Compute', tier: 'Active', subtheme: 'GPU/Compute' },
  { symbol: 'NMR', name: 'Numeraire', theme: 'AI & Compute', tier: 'Active', subtheme: 'Data Marketplace' },
  { symbol: 'ALCH', name: 'Alchemist AI', theme: 'AI & Compute', tier: 'Active', subtheme: 'AI Protocol' },
  // Targeted addition
  { symbol: 'VIRTUAL', name: 'Virtuals Protocol', theme: 'AI & Compute', tier: 'Active', subtheme: 'AI Protocol' },
  { symbol: 'AKT', name: 'Akash Network', theme: 'AI & Compute', tier: 'Active', subtheme: 'Cloud Compute' },
  // Infrastructure
  { symbol: 'LINK', name: 'Chainlink', theme: 'Infrastructure', tier: 'Core', subtheme: 'Oracle' },
  { symbol: 'FIL', name: 'Filecoin', theme: 'Infrastructure', tier: 'Core', subtheme: 'Storage' },
  { symbol: 'WAL', name: 'Walrus', theme: 'Infrastructure', tier: 'Active', subtheme: 'Storage' },
  // Targeted addition — EigenLayer restaking
  { symbol: 'EIGEN', name: 'EigenLayer', theme: 'Infrastructure', tier: 'Active', subtheme: 'Restaking' },
  // Gaming
  { symbol: 'BEAM', name: 'Beam', theme: 'Gaming', tier: 'Active', subtheme: 'Gaming' },
  { symbol: 'ENJ', name: 'Enjin Coin', theme: 'Gaming', tier: 'Active', subtheme: 'NFT' },
  { symbol: 'SPK', name: 'Spark', theme: 'Gaming', tier: 'Active', subtheme: 'Gaming' },
  // Moved from Other (SUPER is a gaming token)
  { symbol: 'SUPER', name: 'SuperVerse', theme: 'Gaming', tier: 'Active', subtheme: 'Gaming' },
  // Targeted addition
  { symbol: 'SAND', name: 'The Sandbox', theme: 'Gaming', tier: 'Active', subtheme: 'Metaverse' },
  // Meme
  { symbol: 'DOGE', name: 'Dogecoin', theme: 'Meme', tier: 'Core', subtheme: 'Meme' },
  { symbol: 'SHIB', name: 'Shiba Inu', theme: 'Meme', tier: 'Core', subtheme: 'Meme' },
  { symbol: 'PEPE', name: 'Pepe', theme: 'Meme', tier: 'Core', subtheme: 'Meme' },
  { symbol: 'M', name: 'MemeCore', theme: 'Meme', tier: 'Active', subtheme: 'Meme' },
  { symbol: 'PUMP', name: 'Pump.fun', theme: 'Meme', tier: 'Active', subtheme: 'Meme' },
  { symbol: 'BANANAS31', name: 'Banana For Scale', theme: 'Meme', tier: 'Active', subtheme: 'Meme' },
  { symbol: 'USELESS', name: 'Useless Coin', theme: 'Meme', tier: 'Active', subtheme: 'Meme' },
  { symbol: 'MELANIA', name: 'Melania Meme', theme: 'Meme', tier: 'Active', subtheme: 'Meme' },
  { symbol: 'SAFE', name: 'Safe', theme: 'Meme', tier: 'Active', subtheme: 'Meme' },
  { symbol: 'TURBO', name: 'Turbo', theme: 'Meme', tier: 'Active', subtheme: 'Meme' },
  { symbol: 'JELLYJELLY', name: 'Jelly-My-Jelly', theme: 'Meme', tier: 'Active', subtheme: 'Meme' },
  { symbol: 'PURR', name: 'Purr', theme: 'Meme', tier: 'Active', subtheme: 'Meme' },
  { symbol: 'BRETT', name: 'Brett', theme: 'Meme', tier: 'Active', subtheme: 'Meme' },
  { symbol: 'BABY', name: 'Babylon', theme: 'Meme', tier: 'Active', subtheme: 'Meme' },
  { symbol: 'POPCAT', name: 'Popcat', theme: 'Meme', tier: 'Active', subtheme: 'Meme' },
  { symbol: 'PNUT', name: 'Peanut the Squirrel', theme: 'Meme', tier: 'Active', subtheme: 'Meme' },
  // Exchange Tokens
  { symbol: 'CRO', name: 'Cronos', theme: 'Exchange Tokens', tier: 'Active', subtheme: 'CEX Token' },
  { symbol: 'OKB', name: 'OKB', theme: 'Exchange Tokens', tier: 'Active', subtheme: 'CEX Token' },
  { symbol: 'O', name: 'o1.exchange', theme: 'Exchange Tokens', tier: 'Active', subtheme: 'CEX Token' },
  // Moved from Other (HTX is the HTX DAO exchange token)
  { symbol: 'HTX', name: 'HTX DAO', theme: 'Exchange Tokens', tier: 'Active', subtheme: 'CEX Token' },
  // Privacy
  { symbol: 'ZEC', name: 'Zcash', theme: 'Privacy', tier: 'Active', subtheme: 'Privacy' },
  { symbol: 'XMR', name: 'Monero', theme: 'Privacy', tier: 'Core', subtheme: 'Privacy' },
  { symbol: 'ZEN', name: 'Horizen', theme: 'Privacy', tier: 'Active', subtheme: 'Privacy L1' },
  { symbol: 'ARX', name: 'Arcium', theme: 'Privacy', tier: 'Active', subtheme: 'Privacy' },
  { symbol: 'CYS', name: 'Cysic', theme: 'Privacy', tier: 'Active', subtheme: 'Privacy' },
  { symbol: 'DUSK', name: 'DUSK', theme: 'Privacy', tier: 'Active', subtheme: 'Privacy' },
  { symbol: 'ROSE', name: 'Oasis', theme: 'Privacy', tier: 'Active', subtheme: 'Privacy' },
  // RWA
  { symbol: 'ONDO', name: 'Ondo', theme: 'RWA', tier: 'Core', subtheme: 'RWA' },
  { symbol: 'CFG', name: 'Centrifuge', theme: 'RWA', tier: 'Active', subtheme: 'Asset Tokenization' },
  { symbol: 'POLYX', name: 'Polymesh', theme: 'RWA', tier: 'Active', subtheme: 'Security Tokens' },
  // Moved from Other (RSR is Reserve Rights — RWA-adjacent)
  { symbol: 'RSR', name: 'Reserve Rights', theme: 'RWA', tier: 'Active', subtheme: 'Stablecoin Infrastructure' },
  // RWA & Payments
  { symbol: 'XLM', name: 'Stellar', theme: 'RWA & Payments', tier: 'Core', subtheme: 'Payments L1' },
  { symbol: 'HBAR', name: 'Hedera', theme: 'RWA & Payments', tier: 'Core', subtheme: 'Payments L1' },
  { symbol: 'ALGO', name: 'Algorand', theme: 'RWA & Payments', tier: 'Active', subtheme: 'Payments L1' },
  { symbol: 'XDC', name: 'XDC Network', theme: 'RWA & Payments', tier: 'Active', subtheme: 'Payments' },
  // Interoperability
  { symbol: 'QNT', name: 'Quant', theme: 'Interoperability', tier: 'Active', subtheme: 'Enterprise' },
  { symbol: 'DBR', name: 'deBridge', theme: 'Interoperability', tier: 'Active', subtheme: 'Bridge' },
  { symbol: 'W', name: 'Wormhole', theme: 'Interoperability', tier: 'Active', subtheme: 'Bridge' },
  { symbol: 'AXL', name: 'Axelar', theme: 'Interoperability', tier: 'Active', subtheme: 'Bridge' },
  // DePIN
  { symbol: 'HNT', name: 'Helium', theme: 'DePIN', tier: 'Active', subtheme: 'Wireless' },
  { symbol: 'PEAQ', name: 'peaq', theme: 'DePIN', tier: 'Active', subtheme: 'IoT' },
  // Other
  { symbol: 'CC', name: 'Canton', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'LAB', name: 'LAB', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'WLFI', name: 'World Liberty Financial', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'ASTER', name: 'Aster', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'PI', name: 'Pi Network', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'BEAT', name: 'Audiera', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'VELVET', name: 'Velvet', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'VVV', name: 'Venice Token', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'AWE', name: 'AWE Network', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'SOSO', name: 'SoSoValue', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'EDGE', name: 'edgeX', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'SENT', name: 'Sentient', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'RAVE', name: 'RaveDAO', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'S', name: 'Sonic', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'ORDI', name: 'ORDI', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'FORM', name: 'Four', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'NXPC', name: 'Nexpace', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'RIVER', name: 'River', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'ZAMA', name: 'Zama', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'HOME', name: 'HOME', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'META', name: 'MetaDAO', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'ALLO', name: 'Allora', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'AIOZ', name: 'AIOZ Network', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'SIREN', name: 'Siren', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'BIO', name: 'Bio Protocol', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'PLUME', name: 'Plume', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'VELO', name: 'Velo', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'ICNT', name: 'Impossible Cloud Network Token', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'SKR', name: 'Seeker', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'JCT', name: 'Janction', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'BSB', name: 'Block Street', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'COAI', name: 'ChainOpera AI', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'APR', name: 'aPriori', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'HOLO', name: 'Holoworld', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'AI', name: 'Gensyn', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: '0G', name: '0G', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'BARD', name: 'Lombard', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'ESP', name: 'Espresso', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  // ── Re-added: covered by Binance perps (with 1000x normalization) ──
  // Layer 1
  { symbol: 'XEC', name: 'eCash', theme: 'Layer 1', tier: 'Active', subtheme: 'Payments' },
  { symbol: 'ELF', name: 'aelf', theme: 'Layer 1', tier: 'Active', subtheme: 'Smart Contract L1' },
  { symbol: 'DGB', name: 'DigiByte', theme: 'Layer 1', tier: 'Active', subtheme: 'Multi-algo Security' },
  // Gaming
  { symbol: 'RON', name: 'Ronin', theme: 'Gaming', tier: 'Active', subtheme: 'Gaming' },
  // Meme
  { symbol: 'SFP', name: 'SafePal', theme: 'Meme', tier: 'Active', subtheme: 'Meme' },
  { symbol: 'CHEEMS', name: 'Cheems Token', theme: 'Meme', tier: 'Active', subtheme: 'Meme' },
  { symbol: 'DEGEN', name: 'Degen', theme: 'Meme', tier: 'Active', subtheme: 'Meme' },
  { symbol: 'BABYDOGE', name: 'Baby Doge Coin', theme: 'Meme', tier: 'Active', subtheme: 'Meme' },
  { symbol: 'TOSHI', name: 'Toshi', theme: 'Meme', tier: 'Active', subtheme: 'Meme' },
  { symbol: 'MOG', name: 'Mog Coin', theme: 'Meme', tier: 'Active', subtheme: 'Meme' },
  // Exchange Tokens
  { symbol: 'LEO', name: 'LEO Token', theme: 'Exchange Tokens', tier: 'Active', subtheme: 'CEX Token' },
  { symbol: 'KCS', name: 'KuCoin', theme: 'Exchange Tokens', tier: 'Active', subtheme: 'CEX Token' },
  // Other (re-added: covered by Binance perps / OKX spot / Bybit spot)
  { symbol: 'NEXO', name: 'NEXO', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: '币安人生', name: '币安人生 (BinanceLife)', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'TAG', name: 'TAGGER', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  // ZIG moved to Layer 1 (ZIGChain is an L1)
  { symbol: 'ZIG', name: 'ZIGChain', theme: 'Layer 1', tier: 'Active', subtheme: 'Smart Contract L1' },
  { symbol: 'CARDS', name: 'Collector Crypt', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'HOT', name: 'Holo', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'KUB', name: 'KUB Coin', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'OMI', name: 'ECOMI', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'IDOL', name: 'MEET48', theme: 'Other', tier: 'Active', subtheme: 'Other' },

];

export const BENCHMARKS = [
  { symbol: 'BTC', name: 'Bitcoin', subtheme: 'Bitcoin' },
  { symbol: 'ETH', name: 'Ethereum', subtheme: 'Smart Contract L1' },
  { symbol: 'SOL', name: 'Solana', subtheme: 'Smart Contract L1' },
  { symbol: 'BNB', name: 'BNB', subtheme: 'Exchange L1' },
  { symbol: 'HYPE', name: 'Hyperliquid', subtheme: 'Perpetuals L1' },
];

export const ROTATION_PAIRS = [
  { label: 'ETH / BTC',    a: 'ETH',    b: 'BTC',    desc: 'Alt vs store-of-value' },
  { label: 'SOL / ETH',    a: 'SOL',    b: 'ETH',    desc: 'New L1 vs established' },
  { label: 'HYPE / SOL',   a: 'HYPE',   b: 'SOL',    desc: 'Perp DEX L1 vs Smart Contract L1' },
  { label: 'DOGE / BTC',   a: 'DOGE',   b: 'BTC',    desc: 'Speculation vs safety' },
  { label: 'UNI / BTC',    a: 'UNI',    b: 'BTC',    desc: 'DeFi vs Bitcoin' },
];
