// Crypto universe — top 250 by market cap (excluding USD-pegged stablecoins)
// 218 assets across 9 themes

export const CRYPTO_UNIVERSE = [
  // Layer 1
  { symbol: 'EGLD', name: 'MultiversX', theme: 'Layer 1', tier: 'Active', subtheme: 'Smart Contract L1' },
  { symbol: 'SHX', name: 'Stronghold', theme: 'Layer 1', tier: 'Active', subtheme: 'Smart Contract L1' },
  { symbol: 'TBK', name: 'TronBank', theme: 'Layer 1', tier: 'Active', subtheme: 'Smart Contract L1' },
  { symbol: 'BERA', name: 'Berachain', theme: 'Layer 1', tier: 'Active', subtheme: 'Smart Contract L1' },
  { symbol: 'DOG', name: 'Dog (Bitcoin)', theme: 'Layer 1', tier: 'Active', subtheme: 'Smart Contract L1' },
  { symbol: 'TFUEL', name: 'Theta Fuel', theme: 'Layer 1', tier: 'Active', subtheme: 'Smart Contract L1' },
  { symbol: 'FLOW', name: 'Flow', theme: 'Layer 1', tier: 'Active', subtheme: 'Smart Contract L1' },
  { symbol: 'KAVA', name: 'Kava', theme: 'Layer 1', tier: 'Active', subtheme: 'Smart Contract L1' },
  { symbol: 'ROSE', name: 'Oasis', theme: 'Layer 1', tier: 'Active', subtheme: 'Smart Contract L1' },
  { symbol: 'MOVE', name: 'Movement', theme: 'Layer 1', tier: 'Active', subtheme: 'Smart Contract L1' },
  { symbol: 'ASTR', name: 'Astar', theme: 'Layer 1', tier: 'Active', subtheme: 'Smart Contract L1' },
  // Layer 2
  { symbol: 'IMX', name: 'Immutable', theme: 'Layer 2', tier: 'Active', subtheme: 'Rollup' },
  { symbol: 'ZK', name: 'ZKsync', theme: 'Layer 2', tier: 'Active', subtheme: 'Rollup' },
  // DeFi
  { symbol: 'CVX', name: 'Convex Finance', theme: 'DeFi', tier: 'Active', subtheme: 'Derivatives' },
  { symbol: '1INCH', name: '1INCH', theme: 'DeFi', tier: 'Active', subtheme: 'Derivatives' },
  { symbol: 'MAGMA', name: 'Magma Finance', theme: 'DeFi', tier: 'Active', subtheme: 'Derivatives' },
  { symbol: 'SNX', name: 'Synthetix', theme: 'DeFi', tier: 'Active', subtheme: 'Derivatives' },
  { symbol: 'AIPF', name: 'AI Powered Finance', theme: 'DeFi', tier: 'Active', subtheme: 'Derivatives' },
  { symbol: 'QRL', name: 'Quantum Resistant Ledger', theme: 'DeFi', tier: 'Active', subtheme: 'Derivatives' },
  { symbol: 'CYDX', name: 'CyberDEX', theme: 'DeFi', tier: 'Active', subtheme: 'DEX' },
  { symbol: 'QFI', name: 'Quantix Finance', theme: 'DeFi', tier: 'Active', subtheme: 'Derivatives' },
  { symbol: 'YFI', name: 'yearn.finance', theme: 'DeFi', tier: 'Active', subtheme: 'Derivatives' },
  { symbol: 'GMX', name: 'GMX', theme: 'DeFi', tier: 'Active', subtheme: 'Derivatives' },
  { symbol: 'FIUSD', name: 'Sygnum FIUSD Liquidity Fund', theme: 'DeFi', tier: 'Active', subtheme: 'Derivatives' },
  { symbol: 'VVS', name: 'VVS Finance', theme: 'DeFi', tier: 'Active', subtheme: 'Derivatives' },
  { symbol: 'SUSHI', name: 'Sushi', theme: 'DeFi', tier: 'Active', subtheme: 'Derivatives' },
  // AI & Compute
  { symbol: 'TIBBIR', name: 'Ribbita by Virtuals', theme: 'AI & Compute', tier: 'Active', subtheme: 'AI Protocol' },
  { symbol: 'ARC', name: 'AI Rig Complex', theme: 'AI & Compute', tier: 'Active', subtheme: 'AI Protocol' },
  { symbol: 'ARKM', name: 'Arkham', theme: 'AI & Compute', tier: 'Active', subtheme: 'AI Protocol' },
  { symbol: 'UAI', name: 'UnifAI Network', theme: 'AI & Compute', tier: 'Active', subtheme: 'AI Protocol' },
  { symbol: 'IO', name: 'io.net', theme: 'AI & Compute', tier: 'Active', subtheme: 'AI Protocol' },
  { symbol: 'NMR', name: 'Numeraire', theme: 'AI & Compute', tier: 'Active', subtheme: 'AI Protocol' },
  { symbol: 'AIX', name: 'AI XOVIA', theme: 'AI & Compute', tier: 'Active', subtheme: 'AI Protocol' },
  // Gaming
  { symbol: 'BEAM', name: 'Beam', theme: 'Gaming', tier: 'Active', subtheme: 'Gaming' },
  { symbol: 'ENJ', name: 'Enjin Coin', theme: 'Gaming', tier: 'Active', subtheme: 'Gaming' },
  { symbol: 'GCOIN', name: 'Playnance', theme: 'Gaming', tier: 'Active', subtheme: 'Gaming' },
  { symbol: 'SPK', name: 'Spark', theme: 'Gaming', tier: 'Active', subtheme: 'Gaming' },
  { symbol: 'RON', name: 'Ronin', theme: 'Gaming', tier: 'Active', subtheme: 'Gaming' },
  // Meme
  { symbol: 'SFP', name: 'SafePal', theme: 'Meme', tier: 'Active', subtheme: 'Meme' },
  { symbol: 'MELANIA', name: 'Melania Meme', theme: 'Meme', tier: 'Active', subtheme: 'Meme' },
  { symbol: 'SAFE', name: 'Safe', theme: 'Meme', tier: 'Active', subtheme: 'Meme' },
  { symbol: 'TURBO', name: 'Turbo', theme: 'Meme', tier: 'Active', subtheme: 'Meme' },
  { symbol: 'BABYDOGE', name: 'Baby Doge Coin', theme: 'Meme', tier: 'Active', subtheme: 'Meme' },
  { symbol: 'BRETT', name: 'Brett', theme: 'Meme', tier: 'Active', subtheme: 'Meme' },
  { symbol: 'BABY', name: 'Babylon', theme: 'Meme', tier: 'Active', subtheme: 'Meme' },
  { symbol: 'MHORSE', name: 'MEME HORSE', theme: 'Meme', tier: 'Active', subtheme: 'Meme' },
  { symbol: 'POPCAT', name: 'Popcat', theme: 'Meme', tier: 'Active', subtheme: 'Meme' },
  { symbol: 'MOG', name: 'Mog Coin', theme: 'Meme', tier: 'Active', subtheme: 'Meme' },
  // Exchange Tokens
  { symbol: 'O', name: 'o1.exchange', theme: 'Exchange Tokens', tier: 'Active', subtheme: 'CEX Token' },
  // Privacy
  { symbol: 'ARRR', name: 'Pirate Chain', theme: 'Privacy', tier: 'Active', subtheme: 'Privacy' },
  // Other
  { symbol: 'PC0000085', name: 'Tradable LatAm Middle-Market Lender', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'RAVE', name: 'RaveDAO', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'XEC', name: 'eCash', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'DRV', name: 'Derive', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'A', name: 'Vaulta', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'AWE', name: 'AWE Network', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'RLB', name: 'Rollbit Coin', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'PC0000077', name: 'Tradable Singapore Fintech SSL', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'EDGE', name: 'edgeX', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'SOSO', name: 'SoSoValue', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'GLM', name: 'Golem', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'AB', name: 'AB', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'UMXM', name: 'Manadia', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'S', name: 'Sonic', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'SENT', name: 'Sentient', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'KMNO', name: 'Kamino', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'CHEEMS', name: 'Cheems Token', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'GRX', name: 'GRX Chain', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'TKX', name: 'Tokenize Xchange', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'GEOD', name: 'Geodnet', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'SYN', name: 'Synapse', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'MET', name: 'Meteora', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'SMILEK', name: 'Smilek to the Bank', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'EXOD', name: 'EXOD', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'ATH', name: 'Aethir', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'ORDI', name: 'ORDI', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'BANANAS31', name: 'Banana For Scale', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'COW', name: 'CoW Protocol', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'DBR', name: 'deBridge', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'WOULD', name: 'would', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'SN64', name: 'Chutes', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'WM', name: 'WrappedM by M0', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'FORM', name: 'Four', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'VCNT', name: 'ViciCoin', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'PGOLD', name: 'Pleasing Gold', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'LPT', name: 'Livepeer', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'NXPC', name: 'Nexpace', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'LOUZI', name: 'LOUZI', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'CFG', name: 'Centrifuge', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'PC0000101', name: 'Tradable NA Post-Settlement Legal F', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'WAL', name: 'Walrus', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'PC0000023', name: 'Tradable NA Neobank SSTL', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'ZEN', name: 'Horizen', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'NXM', name: 'Nexus Mutual', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'USELESS', name: 'Useless Coin', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'HOME', name: 'HOME', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'QTUM', name: 'Qtum', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'LBT', name: 'Law Blocks AI', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'ORCA', name: 'Orca', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'KTA', name: 'Keeta', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'RIVER', name: 'River', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'BAN', name: 'Comedian', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'SIERRA', name: 'Sierra', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'BRLV', name: 'Crown BRLV', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'GAS', name: 'Gas', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'RSR', name: 'Reserve Rights', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'TEMPLE', name: 'TempleDAO', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'MF-ONE', name: 'Midas mF-ONE', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'Q', name: 'Quack AI', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'XDAI', name: 'XDAI', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'ZRX', name: '0x Protocol', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'FLUID', name: 'Fluid', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'META', name: 'MetaDAO', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'STAU', name: 'STAU', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'ZAMA', name: 'Zama', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'NILA', name: 'MindWaveDAO', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'PMUSD', name: 'Precious Metals USD', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'ALLO', name: 'Allora', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'MAG7.SSI', name: 'MAG7.ssi', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'AIOZ', name: 'AIOZ Network', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'MWC', name: 'MimbleWimbleCoin', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'ZIG', name: 'ZIGChain', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'NXT', name: 'NEXST', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'RVN', name: 'Ravencoin', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'SIREN', name: 'Siren', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'CHIP', name: 'USD.AI', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'PC0000019', name: 'Tradable North America PoS Lender S', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'XAUM', name: 'Matrixdock Gold', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'SWOP', name: 'Swop', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'PROS', name: 'Pharos', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'MGLOBAL', name: 'Midas Fasanara Global', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'SOON', name: 'SOON', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'BIO', name: 'Bio Protocol', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'W', name: 'Wormhole', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'PLUME', name: 'Plume', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'DEGEN', name: 'Degen', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'ALCH', name: 'Alchemist AI', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'JELLYJELLY', name: 'Jelly-My-Jelly', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'ZIL', name: 'Zilliqa', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'ARX', name: 'Arcium', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'XPR', name: 'XPR Network', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'METAL', name: 'Metal Blockchain', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'BSB', name: 'Block Street', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'VELO', name: 'Velo', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'LINEA', name: 'Linea', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'ICNT', name: 'Impossible Cloud Network Token', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'SKR', name: 'Seeker', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'VBILL', name: 'VanEck Treasury Fund', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'KSM', name: 'Kusama', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'CARDS', name: 'Collector Crypt', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'XP', name: 'Xphere', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'SN4', name: 'Targon', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'SUPER', name: 'SuperVerse', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'JCT', name: 'Janction', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'MTBILL', name: 'Midas mTBILL', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'HOT', name: 'Holo', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'BDCA', name: 'BitDCA', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'APES', name: 'APES', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'MEGA', name: 'MegaETH', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'COAI', name: 'ChainOpera AI', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'PC0000081', name: 'Tradable NA Legal Receivables SSL', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'NOCK', name: 'Nockchain', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'CYS', name: 'Cysic', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'ELG', name: 'Escoin', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'ZETA', name: 'ZetaChain', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'BCE', name: 'bitcastle Token', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'FXSAVE', name: 'f(x) USD Saving', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'TROLL', name: 'TROLL', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'QUBIC', name: 'Qubic', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'BASEDHYPE', name: 'BasedHype', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'ELF', name: 'aelf', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'BRZ', name: 'Brazilian Digital', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'PURR', name: 'Purr', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'HOLO', name: 'Holoworld', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'APR', name: 'aPriori', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'MINA', name: 'Mina Protocol', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'UNT', name: 'UnityWallet Token', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'PC0000049', name: 'Tradable Eu/LatAm PoS Financing SST', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'AXL', name: 'Axelar', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'CCD', name: 'Concordium', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'OMI', name: 'ECOMI', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'HNT', name: 'Helium', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'DIEM', name: 'Diem', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'KUB', name: 'KUB Coin', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'TOSHI', name: 'Toshi', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'POLYX', name: 'Polymesh', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'TPT', name: 'Triple Plus', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'AGENTFUN', name: 'AgentFun.AI', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'OSK', name: 'OSK', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'KNTQ', name: 'Kinetiq', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: '0G', name: '0G', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'UPUMP', name: 'Unit Pump', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'DUSK', name: 'DUSK', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'PEAQ', name: 'peaq', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'NAT', name: 'DMT-NAT', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'SN51', name: 'lium', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'MHYPER', name: 'Midas mHYPER', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'CKB', name: 'Nervos Network', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'CTC', name: 'Creditcoin', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'OPCODE', name: 'Opcode', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'BARD', name: 'Lombard', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'DGB', name: 'DigiByte', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'UWU', name: 'Unicorn', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'XYO', name: 'XYO Network', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'PNUT', name: 'Peanut the Squirrel', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'LION', name: 'Loaded Lions', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'ONT', name: 'Ontology', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'MBG', name: 'MBG By Multibank Group', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'ANSEM', name: 'The Black Bull', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'IN', name: 'INFINIT', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'BR', name: 'Bedrock', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'ZCHF', name: 'Frankencoin', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'ESP', name: 'Espresso', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'XNO', name: 'Nano', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'BLUR', name: 'Blur', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'EURI', name: 'Eurite', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'AMP', name: 'Amp', theme: 'Other', tier: 'Active', subtheme: 'Other' },
  { symbol: 'IDOL', name: 'MEET48', theme: 'Other', tier: 'Active', subtheme: 'Other' },
];

export const BENCHMARKS = [
];

export const ROTATION_PAIRS = [
  { label: 'ETH / BTC',    a: 'ETH',    b: 'BTC',    desc: 'Alt vs store-of-value' },
  { label: 'SOL / ETH',    a: 'SOL',    b: 'ETH',    desc: 'New L1 vs established' },
  { label: 'HYPE / SOL',   a: 'HYPE',   b: 'SOL',    desc: 'Perp DEX L1 vs Smart Contract L1' },
  { label: 'DOGE / BTC',   a: 'DOGE',   b: 'BTC',    desc: 'Speculation vs safety' },
  { label: 'UNI / BTC',    a: 'UNI',    b: 'BTC',    desc: 'DeFi vs Bitcoin' },
];
